version: '3.1'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'bank'
      MYSQL_ROOT_PASSWORD: 'bank123'
    volumes:
      - ./mydb:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer:4.7.8
    restart: always
    ports:
      - 8080:8080
